name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:        
      - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract Release Tag and Commit SHA
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=release_tag;]$(echo ${GITHUB_REF##*/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # pull, retag gateway-dev image and push
      - name: Pull gateway-dev image
        run: |
          docker pull envoyproxy/gateway-dev:${{ steps.vars.outputs.sha_short }}
      - name: Retag image
        run: |
          docker tag envoyproxy/gateway-dev:${{ steps.vars.outputs.sha_short }} envoyproxy/gateway:${{ steps.vars.outputs.release_tag }}
      - name: Push image to envoyproxy/gateway
        run: |
          docker push envoyproxy/gateway:${{ steps.vars.outputs.release_tag }}

      - name: Generate Release Manifests
        env:
          EG_TAG_VERSION: ${{ steps.tag_env.outputs.version}}
        run: make release-manifests TAG=${EG_TAG_VERSION}

      - name: Upload Release Manifests
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-artifacts/gatewayapi-crds.yaml
            release-artifacts/install.yaml

        
